# Generated by Django 5.2.5 on 2025-12-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(choices=[('random_forest', 'Random Forest'), ('naive_bayes', 'Naive Bayes'), ('bertopic', 'BERTopic'), ('vader', 'VADER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created'),
        ),
    ]
