# Generated by Django 5.2.5 on 2025-12-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_analysis', '0002_trainingdata_updated_at_alter_mlmodel_model_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiontopiccorrelation',
            name='keywords',
            field=models.JSONField(default=list, help_text='Top keywords for this topic (excluding common words)'),
        ),
    ]
