# Generated by Django 5.2.5 on 2025-09-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='comments',
            field=models.TextField(default='', help_text='Additional comments or feedback'),
        ),
    ]
