# Generated by Django 5.2.5 on 2025-09-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_questionnaireresponse_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireresponse',
            name='comments',
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='review',
            field=models.TextField(default='', help_text='Additional review or feedback'),
        ),
    ]
