# Generated by Django 5.2.5 on 2025-10-01 06:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_comments_to_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Employee Satisfaction Survey', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Instructions for the questionnaire')),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this questionnaire expires')),
                ('is_active', models.BooleanField(default=True)),
                ('max_responses', models.PositiveIntegerField(default=1, help_text='Maximum number of responses allowed')),
                ('current_responses', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialQuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('review', models.TextField(default='', help_text='Additional review or feedback')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='frontend.specialquestionnaire')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='1=Strongly Disagree, 2=Disagree, 3=Neutral, 4=Agree, 5=Strongly Agree', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.questionnairequestion')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_responses', to='frontend.specialquestionnaireresponse')),
            ],
            options={
                'unique_together': {('response', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SpecialSectionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_score', models.FloatField()),
                ('total_questions', models.PositiveIntegerField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_scores', to='frontend.specialquestionnaireresponse')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.questionnairesection')),
            ],
            options={
                'unique_together': {('response', 'section')},
            },
        ),
    ]
