# Generated by Django 5.2.5 on 2025-12-04 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_specialquestionnaire_specialquestionnaireresponse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='is_special_response',
            field=models.BooleanField(default=False, help_text='True if this is from a special questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
        migrations.AddField(
            model_name='questionnaireresponse',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when questionnaire was first submitted'),
        ),
        migrations.AlterField(
            model_name='questionnaireresponse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MLInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('topic_contribution', 'Topic Contribution'), ('sentiment_trend', 'Sentiment Trend'), ('section_correlation', 'Section Correlation'), ('improvement_suggestion', 'Improvement Suggestion')], max_length=50)),
                ('insight_text', models.TextField(help_text='The generated insight text')),
                ('confidence_score', models.FloatField(help_text='ML confidence score (0-1)')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('related_sections', models.ManyToManyField(blank=True, to='frontend.questionnairesection')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='frontend.questionnaireresponse')),
            ],
            options={
                'ordering': ['-confidence_score', '-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MLTopicAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_keywords', models.TextField(help_text='Comma-separated keywords for the main topic')),
                ('topic_contribution_score', models.FloatField(help_text='How much this topic contributes to the section score')),
                ('sentiment_score', models.FloatField(help_text='Sentiment analysis score for this topic')),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_topic_analyses', to='frontend.questionnaireresponse')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.questionnairesection')),
            ],
            options={
                'ordering': ['-topic_contribution_score'],
            },
        ),
    ]
