# Generated by Django 5.2.5 on 2025-12-07 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_questionnaireresponse_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaireresponse",
            name="submitted_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when questionnaire was first submitted",
            ),
        ),
    ]
